"""Top-level Pyxel application class for Matchstick Man.

The player sprite is loaded from the bundled ``matchstick.pyxres`` resource
file (generated by ``tools/gen_resources.py``).  Game logic — tile materials,
fuses, level loading, etc. — will be wired into :meth:`App.update` and
:meth:`App.draw` on subsequent feature branches.
"""

from __future__ import annotations

from pathlib import Path

import pyxel

from matchstick_man.player import Player, PlayerState

WIDTH = 512
HEIGHT = 480
TITLE = "Matchstick Man"

_ASSET_PATH = Path(__file__).parent / "assets" / "matchstick.pyxres"
_SPRITE_SIZE = 16
_SPRITE_Y = 0
_TRANSPARENT = 0  # black is the sprite transparency color

# Maps each player state to its sprite's u-coordinate in image bank 0.
# DEAD reuses the HEADLESS sprite — no head, no movement.
_SPRITE_U: dict[PlayerState, int] = {
    PlayerState.HEADED: 0,
    PlayerState.BURNING: 16,
    PlayerState.HEADLESS: 32,
    PlayerState.DEAD: 32,
}


class App:
    """Top-level Pyxel application.

    Construction initializes the Pyxel runtime (window, palette, sound
    channels) and loads the sprite resource.  Calling :meth:`run` enters the
    blocking frame loop.  The construction-versus-run split exists so the
    class can be exercised in tests with ``pyxel.init(..., headless=True)``
    without immediately blocking on the run loop.
    """

    def __init__(self) -> None:
        pyxel.init(WIDTH, HEIGHT, title=TITLE)
        pyxel.load(str(_ASSET_PATH))
        self._player = Player()
        self._player_x = WIDTH // 2 - _SPRITE_SIZE // 2
        self._player_y = HEIGHT // 2 - _SPRITE_SIZE // 2

    def run(self) -> None:
        """Enter Pyxel's blocking update/draw loop. Returns when the user quits."""
        pyxel.run(self.update, self.draw)

    def update(self) -> None:
        """Advance one frame of game state. Currently a no-op."""

    def draw(self) -> None:
        """Render one frame: black background with the player sprite."""
        pyxel.cls(0)
        pyxel.blt(
            self._player_x,
            self._player_y,
            0,
            _SPRITE_U[self._player.state],
            _SPRITE_Y,
            _SPRITE_SIZE,
            _SPRITE_SIZE,
            _TRANSPARENT,
        )
