"""Top-level Pyxel application class for Matchstick Man.

The player sprite is loaded from the bundled ``matchstick.pyxres`` resource
file (generated by ``tools/gen_resources.py``).  Tile materials, fuses, level
loading, etc. will be wired into :meth:`App.update` and :meth:`App.draw` on
subsequent feature branches.
"""

from __future__ import annotations

from pathlib import Path

import pyxel

from matchstick_man.player import Player, PlayerState

WIDTH = 512
HEIGHT = 480
TITLE = "Matchstick Man"

_ASSET_PATH = Path(__file__).parent / "assets" / "matchstick.pyxres"
_SPRITE_SIZE = 16
_SPRITE_Y = 0
_TRANSPARENT = 0  # black is the sprite transparency color

# Floor sits at the bottom of the screen (no tile system yet).
_FLOOR_Y = float(HEIGHT - _SPRITE_SIZE)

# Maps each player state to its sprite's u-coordinate in image bank 0.
# DEAD reuses the HEADLESS sprite — no head, no movement.
_SPRITE_U: dict[PlayerState, int] = {
    PlayerState.HEADED: 0,
    PlayerState.BURNING: 16,
    PlayerState.HEADLESS: 32,
    PlayerState.DEAD: 32,
}


class App:
    """Top-level Pyxel application.

    Construction initializes the Pyxel runtime (window, palette, sound
    channels) and loads the sprite resource.  Calling :meth:`run` enters the
    blocking frame loop.  The construction-versus-run split exists so the
    class can be exercised in tests with ``pyxel.init(..., headless=True)``
    without immediately blocking on the run loop.
    """

    def __init__(self) -> None:
        pyxel.init(WIDTH, HEIGHT, title=TITLE)
        pyxel.load(str(_ASSET_PATH))
        self._player = Player(
            x=float(WIDTH // 2 - _SPRITE_SIZE // 2),
            y=_FLOOR_Y,
        )

    def run(self) -> None:
        """Enter Pyxel's blocking update/draw loop. Returns when the user quits."""
        pyxel.run(self.update, self.draw)

    def update(self) -> None:
        """Advance one frame of game state."""
        # 1. Poll input
        left = pyxel.btn(pyxel.KEY_LEFT) or pyxel.btn(pyxel.KEY_A)
        right = pyxel.btn(pyxel.KEY_RIGHT) or pyxel.btn(pyxel.KEY_D)
        jump = (
            pyxel.btnp(pyxel.KEY_UP)
            or pyxel.btnp(pyxel.KEY_W)
            or pyxel.btnp(pyxel.KEY_SPACE)
        )
        jump_held = (
            pyxel.btn(pyxel.KEY_UP)
            or pyxel.btn(pyxel.KEY_W)
            or pyxel.btn(pyxel.KEY_SPACE)
        )

        # 2. Apply input (uses on_ground from last frame for jump check)
        self._player.apply_input(left=left, right=right, jump=jump, jump_held=jump_held)

        # 3. Advance state machine and integrate physics
        self._player.update()

        # 4. Reset ground flag before collision detection
        self._player.leave_ground()

        # 5. Floor collision: screen bottom (tile-based floors replace this later)
        if self._player.y >= _FLOOR_Y:
            self._player.land(_FLOOR_Y)

        # 6. Horizontal screen boundaries
        self._player.x = max(0.0, min(self._player.x, float(WIDTH - _SPRITE_SIZE)))

    def draw(self) -> None:
        """Render one frame: black background with the state-correct player sprite."""
        pyxel.cls(0)
        # Negative width mirrors the sprite horizontally when facing left.
        w = _SPRITE_SIZE if self._player.facing_right else -_SPRITE_SIZE
        pyxel.blt(
            int(self._player.x),
            int(self._player.y),
            0,
            _SPRITE_U[self._player.state],
            _SPRITE_Y,
            w,
            _SPRITE_SIZE,
            _TRANSPARENT,
        )
